// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: HelloWorldService.proto

package backend_grpc

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type HelloWorld_SayHello_Recv struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloWorld_SayHello_Recv) Reset() {
	*x = HelloWorld_SayHello_Recv{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HelloWorldService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloWorld_SayHello_Recv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloWorld_SayHello_Recv) ProtoMessage() {}

func (x *HelloWorld_SayHello_Recv) ProtoReflect() protoreflect.Message {
	mi := &file_HelloWorldService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloWorld_SayHello_Recv.ProtoReflect.Descriptor instead.
func (*HelloWorld_SayHello_Recv) Descriptor() ([]byte, []int) {
	return file_HelloWorldService_proto_rawDescGZIP(), []int{0}
}

func (x *HelloWorld_SayHello_Recv) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloWorld_SayHello_Send struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloWorld_SayHello_Send) Reset() {
	*x = HelloWorld_SayHello_Send{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HelloWorldService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloWorld_SayHello_Send) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloWorld_SayHello_Send) ProtoMessage() {}

func (x *HelloWorld_SayHello_Send) ProtoReflect() protoreflect.Message {
	mi := &file_HelloWorldService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloWorld_SayHello_Send.ProtoReflect.Descriptor instead.
func (*HelloWorld_SayHello_Send) Descriptor() ([]byte, []int) {
	return file_HelloWorldService_proto_rawDescGZIP(), []int{1}
}

func (x *HelloWorld_SayHello_Send) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_HelloWorldService_proto protoreflect.FileDescriptor

var file_HelloWorldService_proto_rawDesc = []byte{
	0x0a, 0x17, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x62, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x22, 0x2e, 0x0a, 0x18, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x57, 0x6f, 0x72, 0x6c, 0x64, 0x5f, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x52,
	0x65, 0x63, 0x76, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x18, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x57, 0x6f, 0x72, 0x6c, 0x64, 0x5f, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x53,
	0x65, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x6a, 0x0a, 0x0a, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x57, 0x6f, 0x72, 0x6c, 0x64, 0x12, 0x5c, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x12, 0x26, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x5f, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x5f, 0x53, 0x61, 0x79, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x52, 0x65, 0x63, 0x76, 0x1a, 0x26, 0x2e, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f,
	0x72, 0x6c, 0x64, 0x5f, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x53, 0x65, 0x6e,
	0x64, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x3b, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_HelloWorldService_proto_rawDescOnce sync.Once
	file_HelloWorldService_proto_rawDescData = file_HelloWorldService_proto_rawDesc
)

func file_HelloWorldService_proto_rawDescGZIP() []byte {
	file_HelloWorldService_proto_rawDescOnce.Do(func() {
		file_HelloWorldService_proto_rawDescData = protoimpl.X.CompressGZIP(file_HelloWorldService_proto_rawDescData)
	})
	return file_HelloWorldService_proto_rawDescData
}

var file_HelloWorldService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_HelloWorldService_proto_goTypes = []interface{}{
	(*HelloWorld_SayHello_Recv)(nil), // 0: backend_grpc.HelloWorld_SayHello_Recv
	(*HelloWorld_SayHello_Send)(nil), // 1: backend_grpc.HelloWorld_SayHello_Send
}
var file_HelloWorldService_proto_depIdxs = []int32{
	0, // 0: backend_grpc.HelloWorld.SayHello:input_type -> backend_grpc.HelloWorld_SayHello_Recv
	1, // 1: backend_grpc.HelloWorld.SayHello:output_type -> backend_grpc.HelloWorld_SayHello_Send
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_HelloWorldService_proto_init() }
func file_HelloWorldService_proto_init() {
	if File_HelloWorldService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_HelloWorldService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloWorld_SayHello_Recv); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HelloWorldService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloWorld_SayHello_Send); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_HelloWorldService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_HelloWorldService_proto_goTypes,
		DependencyIndexes: file_HelloWorldService_proto_depIdxs,
		MessageInfos:      file_HelloWorldService_proto_msgTypes,
	}.Build()
	File_HelloWorldService_proto = out.File
	file_HelloWorldService_proto_rawDesc = nil
	file_HelloWorldService_proto_goTypes = nil
	file_HelloWorldService_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HelloWorldClient is the client API for HelloWorld service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloWorldClient interface {
	SayHello(ctx context.Context, in *HelloWorld_SayHello_Recv, opts ...grpc.CallOption) (*HelloWorld_SayHello_Send, error)
}

type helloWorldClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloWorldClient(cc grpc.ClientConnInterface) HelloWorldClient {
	return &helloWorldClient{cc}
}

func (c *helloWorldClient) SayHello(ctx context.Context, in *HelloWorld_SayHello_Recv, opts ...grpc.CallOption) (*HelloWorld_SayHello_Send, error) {
	out := new(HelloWorld_SayHello_Send)
	err := c.cc.Invoke(ctx, "/backend_grpc.HelloWorld/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloWorldServer is the server API for HelloWorld service.
type HelloWorldServer interface {
	SayHello(context.Context, *HelloWorld_SayHello_Recv) (*HelloWorld_SayHello_Send, error)
}

// UnimplementedHelloWorldServer can be embedded to have forward compatible implementations.
type UnimplementedHelloWorldServer struct {
}

func (*UnimplementedHelloWorldServer) SayHello(context.Context, *HelloWorld_SayHello_Recv) (*HelloWorld_SayHello_Send, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterHelloWorldServer(s *grpc.Server, srv HelloWorldServer) {
	s.RegisterService(&_HelloWorld_serviceDesc, srv)
}

func _HelloWorld_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloWorld_SayHello_Recv)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloWorldServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend_grpc.HelloWorld/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloWorldServer).SayHello(ctx, req.(*HelloWorld_SayHello_Recv))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloWorld_serviceDesc = grpc.ServiceDesc{
	ServiceName: "backend_grpc.HelloWorld",
	HandlerType: (*HelloWorldServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloWorld_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "HelloWorldService.proto",
}
